version: 2
jobs:
  node-6.0:
    docker:
      - image: circleci/node:6
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test

  node-12.4:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test

  codecov:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run coverage
      - run: npm run codecov

workflows:
  version: 2
  build:
    jobs:
      - node-6.0
      - node-12.4
      - codecov