version: 2
orbs:
  node: circleci/node@4.7.0
jobs:
  node-12.4:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  build:
    jobs:
      - node-12.4